### ISSUE TITLE
Ad banner creative selections needed

### ISSUE THREAD

**Issue by jonatfoodgroup** [the-food-group/2023-lcs-redesign#4]
- [x] Matt to send ad banner creative
- [x] Should link to [trends article](https://www.mondelezinternationalfoodservice.com/Insights/Trends/five-flavor-and-food-trends-for-2023)

Personally, I'd love for the ad banners to be content modules that are responsive but we can do basic banner ads for now: 
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/122066171/221946035-810a78c6-4850-4476-9e7e-6f6efe8bf422.png">

**Comment by mcasper78** [comment]
built in templates/partials/
Hoping it holds up when merged into the site . has  the link and background image.

**Comment by jonatfoodgroup** [comment]
I uploaded the image file to hubspot in the 2023 website assets folder so we have a hosted file vs template
